name: PR Pipeline Workflow

# Execute PR Pipeline Workflow on pull requests to master
on:
  pull_request:
    branches:
      - main


jobs:
  ##########################################################
  # Lint Job:
  # Install dependencies and execute lint debug
  ##########################################################
  android_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: ./gradlew lint

  ##########################################################
  # Assemble Job:
  # Install dependencies and assemble debug and test APKs
  ##########################################################
  assemble:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Assemble Debug
        run: ./gradlew assembleDebug

      - name: Assemble Debug Android Test
        run: ./gradlew assembleDebugAndroidTest


  ##########################################################
  # Unit Test Job:
  # Install dependencies and execute unit tests
  ##########################################################
  unit_test:
    needs: assemble
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Execute unit tests
      - name: Unit Test
        run: ./gradlew testDebugUnitTest


  ##########################################################
  # Instrumentation Test Job:
  # Install dependencies and execute instrumentation tests
  # - Using macOS to initiate Android Emulator
  ##########################################################
  instrumentation_test:
    needs: assemble
    runs-on: macOS-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Run Instrumentation Tests on Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          script: ./gradlew connectedDebugAndroidTest